### ISSUE TITLE
有考虑出个九天版本的吗

### ISSUE THREAD

**Issue by ShiinaMono** [JingShing/novelai-colab-ver#1]
目前已知cf是被墙的

**Comment by JingShing** [comment]
九天版本是什麼意思？

**Comment by ShiinaMono** [comment]
https://jiutian.10086.cn/
中国移动的colab，可以免费使用v100

**Comment by JingShing** [comment]
我沒有使用過這個，需要研究一下。很歡迎自己拿去改，如果我有時間也會去看一下九天怎麼使用，最近暫時不會改。
