### ISSUE TITLE
请问4chan版对比stable-diffusion-webui除ui之外的有其他优势吗？

### ISSUE THREAD

**Issue by RisaKirisu** [JingShing/novelai-colab-ver#13]
您好，谢谢做出这个教程/整合repo! 我前几天都在用stable-diffusion-webui，有些好奇4chan版对比stable-diffusion-webui除了ui之外的优势，以及“75限制”是什么意思？

**Comment by JingShing** [comment]
webui有75個字數限制，4chan版則取消了這個限制(可以到兩百多個關鍵字)。4chan版的效果會更像官方，不論是編輯畫面還是生成出來的成品效果。不過webui會吃更少的效能，安全性也更高一些。4chan的最低vram要求是8g，而webui版則是4g以上。如果想用更低的vram來架設4chan到本地，可以參考[低vram優化4chan版](https://github.com/JingShing/NovelAI-4chan-lowvram-ver)。

**Comment by RisaKirisu** [comment]
好的，谢谢解答！
