### ISSUE TITLE
有时接入gradio.app时会失败，是什么原因呢？

### ISSUE THREAD

**Issue by ArgusK17** [JingShing/novelai-colab-ver#9]
一开始用的时候完全正常，后来有时候会有SSH的问题。会是因为访问太多被网站ban了吗？

**Comment by JingShing** [comment]
有可能太多人使用？public的使用本身就不太穩定

**Comment by ArgusK17** [comment]
能稍微讲解一下这个的原理吗？
想看看能不能让它更稳定一点

**Comment by JingShing** [comment]
建議用新版的4chan版本，或許可以改善這個問題。舊版的之後不會再更新了。

**Comment by ArgusK17** [comment]
好的，非常感谢
